config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.

  devise_for :users

  root to: "homes#index"

  resources :products do
   resources :comments
  end

  resources :orders
  
  resources :homes do
    member do
      get :switch_role
      get :profile
    end
  end

  resources :cart_items do
    collection do
      post  :update_quantity
    end
  end


  post 'cart_items/:id/add' => "cart_items#add_quantity", as: "cart_item_add"
  post 'cart_items/:id/reduce' => "cart_items#reduce_quantity", as: "cart_item_reduce"

end



    

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items

  def add_product(product_id)
    current_item = cart_items.find_by(product_id: product_id)
    if current_item
      current_item.increment(:quantity)
    else
      current_item = cart_items.build(product_id: product_id)
    end
    current_item
  end

  # def total_price
  #   cart_items.to_a.sum { |item| item.total_price }
  # end

  def sub_total
    sum = 0
    self.cart_items.each do |cart_item|
     sum+= cart_item.total_price
    end
    return sum
  end
 
end
  

app/models/cart_item.rb
class CartItem < ApplicationRecord
belongs_to :cart
belongs_to :product

def total_price
  product.price.to_i * quantity.to_i
end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
end
    

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :products

  enum order_status: {pending:0, completed:1 ,failed:2}
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :product_image , dependent: :destroy
  has_many :order_items
  has_many :cart_items, dependent: :destroy
  has_and_belongs_to_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_empty_cart

  has_many :products
  has_many :orders
  has_one :cart

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable,
    :confirmable

  validates :user_name, presence: true
  validates :email, presence: true
    
  enum role: {buyer:0, admin:1 ,seller:2}

  def create_empty_cart
    self.create_cart
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include DeviseSignupWhitelist

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart, only: [:index, :create, :show, :update_quantity]
  before_action :set_product, only: [:create]
  before_action :set_cart_item, only: [:update_quantity, :destroy]

  def index
    @cartitems = @cart.cart_items
  end

  def show
    @cartitem = @cart.cart_items
  end

  def new
    @cartitem = CartItem.new
  end

  def create
    @cartitem = @cart.add_product(@product.id)
    if @cartitem.save
      redirect_to cart_item_path(@cart), notice: "product added to cart"
    end 
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    if @cart_item.present?
      @cart_item.destroy
      redirect_to cart_item_path(@cart_item)
    end
  end  

    # def update_quantity
    #   @cart_item.update(quantity: params[:qty])
    #   render json: {
    #     "item-price-#{@cart_item.id}" => @cart_item.total_price,
    #     total_price: @cart.total_price
    #   }
    # end

  def add_quantity
    @cart_item = CartItem.find(params[:id])
    @cart_item.quantity += 1
    @cart_item.save
    redirect_to cart_item_path(@cart_item)
  end
  
  def reduce_quantity
    @cart_item = CartItem.find(params[:id])
    if @cart_item.quantity > 1
      @cart_item.quantity -= 1
    end
    @cart_item.save
    redirect_to cart_item_path(@cart_item)
  end

  private

  def set_cart
    @cart = current_user.cart
  end

  def set_cart_item
   @cart_item = CartItem.find_by_id(params[:id])
  end

  def set_product
    @product = Product.find(params[:id])
    return if @product.present?
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = CartItem.all
  end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.create(comment_params)
    @comment.Commentor = current_user.user_name
    @comment.save
    redirect_to product_path(@product)
  end
  def destroy
      @product = Product.find(params[:product_id])  
      @comment = @product.comments.find(params[:id]) 
      @comment.destroy 
      redirect_to product_path(@product) 
   end  

  private
    def comment_params
      params.require(:comment).permit(:Commentor, :comment)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @products = Product.all
  end

  def profile
    @user = User.find(params[:id])
    @products = Product.where("user_id=?", current_user.id)
  end

  def switch_role
    @user=User.find(params[:id])
    if @user.buyer?
      @user.seller!
    else
      @user.buyer!
    end
    redirect_to root_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :index]
  
  def index
    @products = Product.find_by(params[:id]) 
    @orders = Order.all
  end

  def show
  end

  def new
    @product = Product.find(params[:product_id])
    @order = Order.new
  end

  def create
    @product = Product.find_by(params[:product_id])
    @order = Order.new(order_params)
    @order.user_id = current_user.id
        if @order.save  
          flash[:notice] = 'order created'
          redirect_to order_path(@order)   
        else
          flash[:error] = 'Failed to add order!'
          render :new
        end 
  end

  private

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:final_price, :order_status, :delivered_at, :shipping_address)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    # GET method to get all products from database   
  def index   
    @products = Product.all   
  end   
  
  # GET method to get a product by id   
  def show   
    @product = Product.find(params[:id])   
  end   
  
  # GET method for the new product form   
  def new
    @product = Product.new   
  end   

  # POST method for processing form data   
  def create 
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    if @product.save   
      flash[:notice] = 'Product added!'
      redirect_to root_path   
    else
      flash[:error] = 'Failed to edit product!'
      render :new
    end   
  end
  
  # GET method for editing a product based on id   
  def edit   
    @product = Product.find(params[:id])   
  end   
  
  # PUT method for updating in database a product based on id   
  def update   
    @product = Product.find(params[:id])   
    if @product.update_attributes(product_params)   
      flash[:notice] = 'Product updated!'   
      redirect_to products_path   
    else   
      flash[:error] = 'Failed to edit product!'   
      render :edit   
    end   
  end   
  
  # DELETE method for deleting a product from database based on id   
  def destroy   
    @product = Product.find(params[:id])   
    if @product.delete   
      flash[:notice] = 'Product deleted!'   
      redirect_to root_path   
    else   
      flash[:error] = 'Failed to delete this product!'   
      render :destroy   
    end   
  end   

  private
  
  # we used strong parameters for the validation of params   
  def product_params   
    params.require(:product).permit(:product_name, :price, :description, :user_id, :product_image)   
  end   
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart_items/_cart_item.html.erb
<ul>
	<% @cartitem.all.each do |cart_item| %>
		<li>
			Product Name: <%= cart_item.product.product_name %><br>
			Description: <%= cart_item.product.description %><br>
			Price: <%= cart_item.product.price %><br>
			<div >   
				<label>Quantity:</label>   
				<%= number_field_tag 'quantity' , cart_item.quantity ,id: cart_item.id , min: 0, class:"my-select-box" %>   
			</div><br>

			<div>   
				<label>Item Price:</label>   
					<td class="item-price-<%= cart_item.id %>"><%= number_to_currency(cart_item.total_price) %></td>
			</div><br>

			<div>
				<%=  link_to "Add quantity", cart_item_add_path(:id => cart_item), method: :post, class:"bg-blue-500 hover:bg-blue-700 text-white py-2 px-2 rounded"%>  
				<%= link_to "Reduce quantity", cart_item_reduce_path(:id => cart_item), method: :post, class:"bg-blue-500 hover:bg-blue-700 text-white py-2 px-2 rounded" %>
			</div><br>
        <%= link_to "Remove item" ,cart_item_path(cart_item) , method:  :delete, class:"bg-blue-500 hover:bg-blue-700 text-white py-2 px-2 rounded" %>
	 </li>
	<% end %>
</ul>

app/views/cart_items/show.html.erb
<%= render "cart_item" %>

app/views/comments/_comment.html.erb
<h2>Reviews</h2>
<h2>Add a comment:</h2>
<%= form_with(model: [ @product, @product.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :comment %><br>
    <%= form.text_area :comment %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/products/_form.html.erb
<%= form_for(@product)  do |form| %>
	<p>
		<%= form.label :Product_Name %><br>
		<%= form.text_field :product_name %>
	</p>

	<p>
		<%= form.label :Description %><br>
		<%= form.text_area :description %>
	</p>

	<p>
		<%= form.label :Price %><br>
		<%= form.number_field :price %>
	</p>

	<p>
		<%= form.label :Product_image %><br>
		<%= form.file_field :product_image %>
	</p>

	<p>
		<%= form.submit %>
	</p>

<% end %>

app/views/products/_products_table.html.erb
<!DOCTYPE html>   
<html>     
	<body>   
		<div class="container"><br>
			<h3>product list</h3><br>   
			<table>   
				<thead>   
					<tr>   
						<th>Name</th>   
						<th>Price</th>   
						<th>Description</th>  
				  </tr>   
				</thead>   
					<tbody> 
						<% @products.all.each do |product| %>   
							<% if (user_signed_in? && current_user.seller?) %> 
								<tr>   
									<td><%= product.product_name %></td>   
									<td><%= product.price %></td>   
									<td><%= truncate(product.description, :length => 75) %></td>   
									<div>
										<% if product.user_id == current_user.id %>  
											<td>   
												<%= link_to 'Show', product_path(product) %>   
												<%= link_to 'Edit', edit_product_path(product) %>   
												<%= link_to 'Delete', product_path(product), method: :delete %>   
											</td> 
										<% end %>
									</div>
								</tr>
							<% else %>
								<tr>
									<td><%= link_to product.product_name, product_path(product) %></td>   
									<td><%= product.price %></td>   
									<td><%= truncate(product.description, :length => 75) %></td> 
								</tr>    
							<% end %>  
						<% end %>   
					</tbody>   
			</table><br>
				<div>
					<% if user_signed_in? && current_user.seller?  %>   
							<%= link_to 'Add Product', new_product_path %>
					<% end %>   
				</div>     
		</div>   
	</body>   
</html>

app/views/products/edit.html.erb
<div class="container">   
	<%= form_for @product, url: {action: :update} do |f| %>   
		<h3>Update a Product</h3> 
			<%= "<div>#{@product.errors.full_messages.first}</div>".html_safe if @product.errors.any? %>    
				<div>   
					<label>Product Name</label> <br>  
					<%= f.text_field :product_name %>   
				</div>

				<div>   
					<label>Price</label><br> 
					<%= f.text_field :price %>   
				</div>

				<div>   
					<label>Description</label><br> 
					<%= f.text_field :description %>   
				</div>

				<div>
					<%= f.label :Product_image %><br>
					<%= f.file_field :product_image %>
				</div>   

				<div>   
				<%= link_to 'Back', { controller: 'products', action: 'index'} %>   
				<%= f.submit 'Update Product' %>
	<% end %>    
</div>   

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
<div class="container">
	<div>
	  <%  if @product.product_image.attached? %>
			<%= image_tag(@product.product_image, alt: "Image is not available", height: 600, width: 600) %>
		<% end %>
	</div>

	<div>   
		<label>Created by</label>   
		<%= @product.user.user_name %>   
	</div> 

	<div>   
		<label>Product Name:</label>   
		<%= @product.product_name %>   
	</div>

	<div>   
		<label>Price:</label>   
		<%= @product.price %>   
	</div>   
			
	<div>   
		<label>Description:</label>   
		<%= @product.description %>   
	</div><br>


	<div>
		<% if user_signed_in? && current_user.buyer? %>
			<%= link_to "Buy Now", new_order_path(:product_id => @product.id), class:"bg-blue-500 hover:bg-blue-700 text-white py-2 px-2 rounded" %>
			<%= link_to "Add to cart", cart_items_path(id: @product.id), method: :post , class:"bg-blue-500 hover:bg-blue-700 text-white py-2 px-2 rounded" %>
		<% elsif user_signed_in? && current_user.present? %>	
			<%= link_to " " %>
    <% else %> 
			<%= link_to "purchase product", new_user_session_path , class:"bg-blue-500 hover:bg-blue-700 text-white py-2 px-2 rounded" %>
		<% end %>
	</div><br>	

</div>

<%=render 'comments/comment' %> 

	<h1>Reviews</h1>
	
<% @product.comments.each do |c|  %>
	<hr>
		<h2>Commentor:<%= c.Commentor %></h2>
			<h2>Comment:<%= c.comment %></h2>
			<% if user_signed_in? && c.Commentor == current_user.user_name %>
				<p>
					<%= link_to 'Delete Comment', [c.product, c],
										method: :delete,
										data: { confirm: "Are you sure?" }, class: 'mx-5 px-6 py-2 my-10 text-white bg-red-600 rounded-lg hover:bg-blue-900' %>
				</p>
			<% end %>
	<hr>
<% end %>