config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.

  devise_for :users

  root to: "homes#index"

  resources :products do
   resources :comments
  end

  resources :orders
  
  resources :homes do
    member do
      get :switch_role
      get :profile
    end
  end

  resources :cart_items do
    collection do
      post  :update_quantity
    end
  end


  post 'cart_items/:id/add' => "cart_items#add_quantity", as: "cart_item_add"
  post 'cart_items/:id/reduce' => "cart_items#reduce_quantity", as: "cart_item_reduce"

end



    

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items

  def add_product(product_id)
    current_item = cart_items.find_by(product_id: product_id)
    if current_item
      current_item.increment(:quantity)
    else
      current_item = cart_items.build(product_id: product_id)
    end
    current_item
  end

  # def total_price
  #   cart_items.to_a.sum { |item| item.total_price }
  # end

  def sub_total
    sum = 0
    self.cart_items.each do |cart_item|
     sum+= cart_item.total_price
    end
    return sum
  end
 
end
  

app/models/cart_item.rb
class CartItem < ApplicationRecord
belongs_to :cart
belongs_to :product

def total_price
  product.price.to_i * quantity.to_i
end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
end
    

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :products

  enum order_status: {pending:0, completed:1 ,failed:2}
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :product_image , dependent: :destroy
  has_many :order_items
  has_many :cart_items, dependent: :destroy
  has_and_belongs_to_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_empty_cart

  has_many :products
  has_many :orders
  has_one :cart

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable,
    :confirmable

  validates :user_name, presence: true
  validates :email, presence: true
    
  enum role: {buyer:0, admin:1 ,seller:2}

  def create_empty_cart
    self.create_cart
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = CartItem.all
  end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.create(comment_params)
    @comment.Commentor = current_user.user_name
    @comment.save
    redirect_to product_path(@product)
  end
  def destroy
      @product = Product.find(params[:product_id])  
      @comment = @product.comments.find(params[:id]) 
      @comment.destroy 
      redirect_to product_path(@product) 
   end  

  private
    def comment_params
      params.require(:comment).permit(:Commentor, :comment)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @products = Product.all
  end

  def profile
    @user = User.find(params[:id])
    @products = Product.where("user_id=?", current_user.id)
  end

  def switch_role
    @user=User.find(params[:id])
    if @user.buyer?
      @user.seller!
    else
      @user.buyer!
    end
    redirect_to root_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :index]
  
  def index
    @products = Product.find_by(params[:id]) 
    @orders = Order.all
  end

  def show
  end

  def new
    @product = Product.find(params[:product_id])
    @order = Order.new
  end

  def create
    @product = Product.find_by(params[:product_id])
    @order = Order.new(order_params)
    @order.user_id = current_user.id
        if @order.save  
          flash[:notice] = 'order created'
          redirect_to order_path(@order)   
        else
          flash[:error] = 'Failed to add order!'
          render :new
        end 
  end

  private

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:final_price, :order_status, :delivered_at, :shipping_address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_navigation.html.erb
<nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded bg-blue-800">
	<div class="container flex flex-wrap justify-between items-center mx-6 ">
    <%= image_tag "logo.png", class:"h-20" %>
		<button data-collapse-toggle="mobile-menu" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="mobile-menu" aria-expanded="false">
			<span class="sr-only">Open main menu</span>
			<svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
			<svg class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
		</button>

		<div class="hidden w-full md:block md:w-auto md:bg-transparent md:text-white-700" id="mobile-menu">
			<ul class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium block py-2 pr-4 pl-3 text-white bg-blue-700 rounded md:bg-transparent md:text-white-700 md:p-0 dark:text-white">
				<li>
					<%= link_to "Home", root_path, class:"block py-2 pr-4 pl-3 text-white bg-blue-700 rounded md:bg-transparent md:text-white-700 md:p-0 dark:text-white"  %>
				</li>
				<% if user_signed_in? %>
					<li class="block py-2 pr-4 pl-3 text-white bg-blue-700 rounded md:bg-transparent md:text-white-700 md:p-0 dark:text-white"> 
						<% if current_user.buyer? %>
							<%= link_to "Become a seller",  switch_role_home_path(current_user) %><br/>
						<% else %>
							<%= link_to "Create a Product",  new_product_path %><br/>
							<%= link_to "Become a buyer",  switch_role_home_path(current_user) %><br/>
						<% end %>
					</li>

					<li>
						<p>current role is <%= current_user.role  %> 
					</li>

					<li>
						<i class="fa-solid fa-user fa-lg"></i>
						<%= link_to current_user.user_name, profile_home_path(current_user.id) %>
					</li>

					<li>
					 <i class="fas fa-shopping-cart"></i>
					 <%= link_to current_user.user_name %>
					</li>
          
					<li>
						<%= link_to "Logout", destroy_user_session_path, method: :delete , class: 'px-6 py-2 mt-4 text-white bg-dark-600 rounded-lg hover:bg-blue-900' %>
					</li>

				<% else %>
					<div class="w-full">
						<div class="float-right">
							<%= link_to "Login", new_user_session_path, class: 'px-6 py-2 mr-3 text-white bg-blue-600 rounded-lg hover:bg-blue-900' %>
							<%= link_to "Signup", new_user_registration_path, class: 'mr-12 px-6 py-2  text-white bg-blue-600 rounded-lg hover:bg-blue-900' %>
						</div>
					</div>
				<% end %>
			</ul>
		</div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lockerapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <script src="https://cdn.tailwindcss.com"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>